services:
  api-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - product-service
    #   - user-service
    #   - order-service
    #   - payment-service
    #   - inventory-service
