version: "1.0"

services:
  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - product-service
      - user-service
      - order-service
      - payment-service
      - inventory-service
